import './globals.css'
import { ReactNode } from 'react'
import {
  Roboto_Flex as Roboto,
  Bai_Jamjuree as BaiJamjuree,
} from 'next/font/google'
import { Navbar } from '@/components/Navbar'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjurree',
})

export const metadata = {
  title: 'Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${baiJamjuree.variable} bg-gray-800 h-screen relative`}
      >
        <Navbar />
        {/* Blur */}
        {/* <div className="absolute top-1/2 h-[288px] w-[526px] -translate-y-1/2 right-1/2 translate-x-1/2 rounded-full bg-pallete-lightgold opacity-70 blur-full" /> */}
        <div className="flex justify-center items-center h-full">
          {children}
        </div>
      </body>
    </html>
  )
}
