import './globals.css'
import { ReactNode } from 'react'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex w-full justify-center items-center bg-gray-500">
          <ul className="flex gap-4">
            <Link href="/">
              <li>Home</li>
            </Link>
            <Link href="/notes">
              <li>Notes</li>
            </Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
